sonar.organization=rkristelijn
sonar.projectKey=rkristelijn_cpm
sonar.projectName=cpm

sonar.sources=src,lib,checks
sonar.tests=tests
sonar.exclusions=vendor/**,build/**,.tmp/**,node_modules/**

sonar.cpd.minimumTokens=50
sonar.cpd.minimumLines=10

sonar.coverageReportPaths=.tmp/cov/coverage.xml
