#!/usr/bin/env bash
# generate-process.sh — Generate PROCESS.md based on maturity-target in cpm.toml.
# Usage: bash lib/shell/generate-process.sh > PROCESS.md
# Regenerate when maturity-target changes.
set -o errexit
set -o nounset
set -o pipefail

TARGET=$(grep -A5 '^\[process\]' cpm.toml 2>/dev/null | sed -n 's/^maturity-target *= *//p' | tr -d ' ')
TARGET="${TARGET:-1}"

cat <<'EOF'
# Way of Working

> Auto-generated by `cpm`. Regenerate: `bash lib/shell/generate-process.sh > PROCESS.md`

EOF

echo "**Maturity target: level $TARGET**"
echo ""

# Level 1: basics
cat <<'EOF'
## Commit conventions

All commits follow [Conventional Commits](https://www.conventionalcommits.org/):

```
type(scope): description
```

Types: `feat` `fix` `docs` `test` `refactor` `chore` `ci` `perf` `style` `build`

EOF

if ((TARGET >= 2)); then
cat <<'EOF'
## Branch strategy

- `main` is protected — no direct code commits
- Feature branches: `feat/<issue#>-<slug>`
- Fix branches: `fix/<issue#>-<slug>`
- Docs/config changes may go directly to main

### Workflow

```
cpm issue "type: title"     → create ticket
cpm issue branch <slug>     → create branch from ticket
# work...
cpm commit                  → conventional commit with scope = issue
git push -u origin <branch> → push branch
# create PR → review → merge
```

EOF
fi

if ((TARGET >= 3)); then
cat <<'EOF'
## Quality gates

| Gate | When | What |
|------|------|------|
| pre-commit | `git commit` | process check + `cpm check --fast` |
| commit-msg | `git commit` | conventional format + issue reference |
| pre-push | `git push` | block main + `cpm check` |

### Rules at this level

- **feat/fix commits must reference an issue** (scope or `closes #N`)
- **Code changes require tests** in the same commit
- **All checks must pass** before push

## Issue tracking

Issues live in `docs/issues/open/` as markdown files:

```
cpm issue "feat: title"     → create with template
cpm issue push              → sync to GitHub
cpm issue pull              → download remote issues
cpm issue branch <slug>     → create branch
cpm issue close <slug>      → archive
```

### Templates scale with type

| Type | Sections |
|------|----------|
| feat | What, Why, Done when (acceptance criteria) |
| fix | Problem, Reproduce, Expected vs actual, Done when |
| chore | What |

EOF
fi

if ((TARGET >= 4)); then
cat <<'EOF'
## Release process

- All acceptance criteria checked off before merge
- Regression test suite passes
- Version bump: `cpm bump minor`
- Tag + release notes generated

## Architecture enforcement

- Import boundaries validated
- No dead code
- Mutation testing passes
- DORA metrics tracked

EOF
fi

cat <<EOF
---
*Generated for maturity level $TARGET. Change target: \`cpm set process.maturity-target <N>\`*
EOF
