#!/usr/bin/env bash
# fixes/nextjs-ci.sh — Generate GitHub Actions CI workflow based on what the project actually has
set -o errexit -o nounset -o pipefail

REPO="${1:-.}"
PKG="$REPO/package.json"
WORKFLOW_DIR="$REPO/.github/workflows"

[ -f "$PKG" ] || { echo "  ✗ No package.json"; exit 1; }

# Already has CI?
if [ -d "$REPO/.github/workflows" ] && ls "$WORKFLOW_DIR"/*.yml >/dev/null 2>&1; then
  echo "  ✓ CI workflow already exists"
  exit 0
fi

# Detect what's available
HAS_LINT=false
HAS_TEST=false
HAS_BUILD=false
grep -q '"lint"' "$PKG" && HAS_LINT=true
grep -q '"test"' "$PKG" && ! grep -q '"test".*"echo' "$PKG" && HAS_TEST=true
grep -q '"build"' "$PKG" && HAS_BUILD=true

# Detect package manager
if [ -f "$REPO/pnpm-lock.yaml" ]; then
  PM="pnpm"
  INSTALL="pnpm install --frozen-lockfile"
  SETUP_PM='      - uses: pnpm/action-setup@v4'
  CACHE="pnpm"
elif [ -f "$REPO/yarn.lock" ]; then
  PM="yarn"
  INSTALL="yarn --frozen-lockfile"
  SETUP_PM=""
  CACHE="yarn"
else
  PM="npm"
  INSTALL="npm ci"
  SETUP_PM=""
  CACHE="npm"
fi

# Detect node version
NODE_VER="22"
[ -f "$REPO/.nvmrc" ] && NODE_VER=$(cat "$REPO/.nvmrc" | tr -d 'v \n')
[ -f "$REPO/.node-version" ] && NODE_VER=$(cat "$REPO/.node-version" | tr -d 'v \n')

mkdir -p "$WORKFLOW_DIR"

# Build the workflow
cat > "$WORKFLOW_DIR/ci.yml" << EOF
# Generated by: cpm fix ci
# Based on: package.json (${PM}, node ${NODE_VER}, lint: ${HAS_LINT}, test: ${HAS_TEST}, build: ${HAS_BUILD})
name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${SETUP_PM}
      - uses: actions/setup-node@v4
        with:
          node-version: '${NODE_VER}'
          cache: '${CACHE}'
      - run: ${INSTALL}
EOF

if [ "$HAS_LINT" = true ]; then
  echo "      - run: $PM run lint" >> "$WORKFLOW_DIR/ci.yml"
fi
if [ "$HAS_TEST" = true ]; then
  echo "      - run: $PM run test" >> "$WORKFLOW_DIR/ci.yml"
fi
if [ "$HAS_BUILD" = true ]; then
  echo "      - run: $PM run build" >> "$WORKFLOW_DIR/ci.yml"
fi

# Report what was generated
echo "  ✓ Created .github/workflows/ci.yml"
echo "    Steps: install$([ "$HAS_LINT" = true ] && echo ", lint")$([ "$HAS_TEST" = true ] && echo ", test")$([ "$HAS_BUILD" = true ] && echo ", build")"
